#include "g_local.h"


void G_OSPAuth(const gentity_t* ent);
void Cmd_ViewList_f(const gentity_t* ent);
void Cmd_GetStatsInfo_f(const gentity_t* ent);
void Cmd_Stats_f(const gentity_t* ent, int arg);
void Cmd_StatsAll_f(const gentity_t* ent, int arg);
void Cmd_Acc_f(const gentity_t* ent, int arg);
void Cmd_OSPAuth_f(const gentity_t* ent);
void Cmd_ScoresFT_f(const gentity_t* ent, int arg);
void Cmd_ScoresDM_f(const gentity_t* ent, int arg);
void Cmd_ScoresCTF_f(const gentity_t* ent, int arg);
void Cmd_ScoresCA_f(const gentity_t* ent, int arg);
void Cmd_ScoresFFA_f(const gentity_t* ent, int arg);
qboolean Cmd_CallVote2_f(const gentity_t* ent, int arg);
void Cmd_RefHelp(const gentity_t* ent);
qboolean Cmd_RefCommandArg_f(const gentity_t* ent, const char* arg, qboolean unk);
void Cmd_Lock_f(const gentity_t* ent, char* arg);
void Cmd_SpecLock_f(const gentity_t* ent, char* arg);
void Cmd_Ready_f(const gentity_t* ent, qboolean unk);
void Cmd_TeamReady_f(const gentity_t* ent);
void Cmd_Invite_f(const gentity_t* ent);
void Cmd_SpecInvite_f(const gentity_t* ent);
void Cmd_Remove_f(const gentity_t* ent);
void Cmd_Capitans_f(const gentity_t* ent);
void Cmd_Resign_f(const gentity_t* ent);
void Cmd_JoinCode_f(const gentity_t* ent);
void Cmd_Pause_f(const gentity_t* ent, qboolean unk);
void Cmd_SpecOnly_f(const gentity_t* ent);
void Cmd_AutoScreenshot_f(int entityNum, qboolean unk1, qboolean unk2);
void Cmd_MapList_f(const gentity_t* ent);
void Cmd_MapLoad_f(qboolean unk);
void Cmd_Range_f(const gentity_t* ent);
void Cmd_Snapshot_f(const gentity_t* ent);
void Cmd_SnapshotDump_f(const gentity_t* ent);
void Cmd_ViewAdd_f(const gentity_t* ent);
void Cmd_ViewAll_f(const gentity_t* ent);
void Cmd_ViewerMove_f(const gentity_t* ent);
void Cmd_ViewFollow(const gentity_t* ent);
void Cmd_ViewNone_f(const gentity_t* ent);
void Cmd_ViewFrame_f(const gentity_t* ent);
void Cmd_ViewNext_f(const gentity_t* ent, int unk);
void Cmd_ViewCycleNext_f(const gentity_t* ent, int unk);
void Cmd_ViewTeam_f(const gentity_t* ent, int unk1, int unk2);
void Cmd_Coach_f(const gentity_t* ent, qboolean unk);
void Cmd_CoachInvite_f(const gentity_t* ent);
void Cmd_CoachDecline_f(const gentity_t* ent);
void Cmd_CoachKick_f(const gentity_t* ent);
void Cmd_VcProximity_f(const gentity_t* ent);
void Cmd_VcFollow_f(const gentity_t* ent);
void Cmd_Drop_f(const gentity_t* ent);
void Cmd_ViewCam_f(const gentity_t* ent);
void Cmd_Settings_f(const gentity_t* ent);
